services:
  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - redis-net

volumes:
  redis_data:

networks:
  redis-net:
    driver: bridge