version: '3.8'

services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector-db
    environment:
      POSTGRES_DB: ia_educacao_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: